# Generated by Django 5.0.6 on 2024-05-29 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sinf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentlar', to='students.sinf'),
        ),
    ]
